NTRAPS = 2

print("# generated by vector.py - do not edit")
print("global traps")

for i in range(NTRAPS):
    print(f"global vector{i}")

for i in range(NTRAPS):
    print(f"vector{i}:")
    # if(!($i == 8 || ($i >= 10 && $i <= 14) || $i == 17)){
    #     print "  pushl \$0\n";
    # }
    print(f"    pushq {i}")
    print(f"    jmp traps")

# print "\n# vector table\n";
# print ".data\n";
# print ".globl vectors\n";
# print "vectors:\n";
# for(my $i = 0; $i < 256; $i++){
#     print "  .long vector$i\n";
# }

# sample output:
#   # handlers
#   .globl alltraps
#   .globl vector0
#   vector0:
#     pushl $0
#     pushl $0
#     jmp alltraps
#   ...
#   
#   # vector table
#   .data
#   .globl vectors
#   vectors:
#     .long vector0
#     .long vector1
#     .long vector2
#   ...