; generated by vector.py - do not edit
BITS 64
extern trampoline
global vector
vector0:
    push qword 0
    push qword 0
    jmp trampoline
vector1:
    push qword 0
    push qword 1
    jmp trampoline
vector2:
    push qword 0
    push qword 2
    jmp trampoline
vector3:
    push qword 0
    push qword 3
    jmp trampoline
vector4:
    push qword 0
    push qword 4
    jmp trampoline
vector5:
    push qword 0
    push qword 5
    jmp trampoline
vector6:
    push qword 0
    push qword 6
    jmp trampoline
vector7:
    push qword 0
    push qword 7
    jmp trampoline
vector8:
    push qword 8
    jmp trampoline
vector9:
    push qword 0
    push qword 9
    jmp trampoline
vector10:
    push qword 10
    jmp trampoline
vector11:
    push qword 11
    jmp trampoline
vector12:
    push qword 12
    jmp trampoline
vector13:
    push qword 13
    jmp trampoline
vector14:
    push qword 14
    jmp trampoline
vector15:
    push qword 0
    push qword 15
    jmp trampoline
vector16:
    push qword 0
    push qword 16
    jmp trampoline
vector17:
    push qword 17
    jmp trampoline
vector18:
    push qword 0
    push qword 18
    jmp trampoline
vector19:
    push qword 0
    push qword 19
    jmp trampoline
vector20:
    push qword 0
    push qword 20
    jmp trampoline
vector21:
    push qword 21
    jmp trampoline
vector22:
    push qword 0
    push qword 22
    jmp trampoline
vector23:
    push qword 0
    push qword 23
    jmp trampoline
vector24:
    push qword 0
    push qword 24
    jmp trampoline
vector25:
    push qword 0
    push qword 25
    jmp trampoline
vector26:
    push qword 0
    push qword 26
    jmp trampoline
vector27:
    push qword 0
    push qword 27
    jmp trampoline
vector28:
    push qword 0
    push qword 28
    jmp trampoline
vector29:
    push qword 29
    jmp trampoline
vector30:
    push qword 30
    jmp trampoline
vector31:
    push qword 0
    push qword 31
    jmp trampoline
vector32:
    push qword 0
    push qword 32
    jmp trampoline
vector33:
    push qword 0
    push qword 33
    jmp trampoline
vector34:
    push qword 0
    push qword 34
    jmp trampoline
vector35:
    push qword 0
    push qword 35
    jmp trampoline
vector36:
    push qword 0
    push qword 36
    jmp trampoline
vector37:
    push qword 0
    push qword 37
    jmp trampoline
vector38:
    push qword 0
    push qword 38
    jmp trampoline
vector39:
    push qword 0
    push qword 39
    jmp trampoline
vector40:
    push qword 0
    push qword 40
    jmp trampoline
vector41:
    push qword 0
    push qword 41
    jmp trampoline
vector42:
    push qword 0
    push qword 42
    jmp trampoline
vector43:
    push qword 0
    push qword 43
    jmp trampoline
vector44:
    push qword 0
    push qword 44
    jmp trampoline
vector45:
    push qword 0
    push qword 45
    jmp trampoline
vector46:
    push qword 0
    push qword 46
    jmp trampoline
vector47:
    push qword 0
    push qword 47
    jmp trampoline
vector48:
    push qword 0
    push qword 48
    jmp trampoline
vector49:
    push qword 0
    push qword 49
    jmp trampoline
vector50:
    push qword 0
    push qword 50
    jmp trampoline
vector51:
    push qword 0
    push qword 51
    jmp trampoline
vector52:
    push qword 0
    push qword 52
    jmp trampoline
vector53:
    push qword 0
    push qword 53
    jmp trampoline
vector54:
    push qword 0
    push qword 54
    jmp trampoline
vector55:
    push qword 0
    push qword 55
    jmp trampoline
vector56:
    push qword 0
    push qword 56
    jmp trampoline
vector57:
    push qword 0
    push qword 57
    jmp trampoline
vector58:
    push qword 0
    push qword 58
    jmp trampoline
vector59:
    push qword 0
    push qword 59
    jmp trampoline
vector60:
    push qword 0
    push qword 60
    jmp trampoline
vector61:
    push qword 0
    push qword 61
    jmp trampoline
vector62:
    push qword 0
    push qword 62
    jmp trampoline
vector63:
    push qword 0
    push qword 63
    jmp trampoline
vector64:
    push qword 0
    push qword 64
    jmp trampoline
vector65:
    push qword 0
    push qword 65
    jmp trampoline
vector66:
    push qword 0
    push qword 66
    jmp trampoline
vector67:
    push qword 0
    push qword 67
    jmp trampoline
vector68:
    push qword 0
    push qword 68
    jmp trampoline
vector69:
    push qword 0
    push qword 69
    jmp trampoline
vector70:
    push qword 0
    push qword 70
    jmp trampoline
vector71:
    push qword 0
    push qword 71
    jmp trampoline
vector72:
    push qword 0
    push qword 72
    jmp trampoline
vector73:
    push qword 0
    push qword 73
    jmp trampoline
vector74:
    push qword 0
    push qword 74
    jmp trampoline
vector75:
    push qword 0
    push qword 75
    jmp trampoline
vector76:
    push qword 0
    push qword 76
    jmp trampoline
vector77:
    push qword 0
    push qword 77
    jmp trampoline
vector78:
    push qword 0
    push qword 78
    jmp trampoline
vector79:
    push qword 0
    push qword 79
    jmp trampoline
vector80:
    push qword 0
    push qword 80
    jmp trampoline
vector81:
    push qword 0
    push qword 81
    jmp trampoline
vector82:
    push qword 0
    push qword 82
    jmp trampoline
vector83:
    push qword 0
    push qword 83
    jmp trampoline
vector84:
    push qword 0
    push qword 84
    jmp trampoline
vector85:
    push qword 0
    push qword 85
    jmp trampoline
vector86:
    push qword 0
    push qword 86
    jmp trampoline
vector87:
    push qword 0
    push qword 87
    jmp trampoline
vector88:
    push qword 0
    push qword 88
    jmp trampoline
vector89:
    push qword 0
    push qword 89
    jmp trampoline
vector90:
    push qword 0
    push qword 90
    jmp trampoline
vector91:
    push qword 0
    push qword 91
    jmp trampoline
vector92:
    push qword 0
    push qword 92
    jmp trampoline
vector93:
    push qword 0
    push qword 93
    jmp trampoline
vector94:
    push qword 0
    push qword 94
    jmp trampoline
vector95:
    push qword 0
    push qword 95
    jmp trampoline
vector96:
    push qword 0
    push qword 96
    jmp trampoline
vector97:
    push qword 0
    push qword 97
    jmp trampoline
vector98:
    push qword 0
    push qword 98
    jmp trampoline
vector99:
    push qword 0
    push qword 99
    jmp trampoline
vector100:
    push qword 0
    push qword 100
    jmp trampoline
vector101:
    push qword 0
    push qword 101
    jmp trampoline
vector102:
    push qword 0
    push qword 102
    jmp trampoline
vector103:
    push qword 0
    push qword 103
    jmp trampoline
vector104:
    push qword 0
    push qword 104
    jmp trampoline
vector105:
    push qword 0
    push qword 105
    jmp trampoline
vector106:
    push qword 0
    push qword 106
    jmp trampoline
vector107:
    push qword 0
    push qword 107
    jmp trampoline
vector108:
    push qword 0
    push qword 108
    jmp trampoline
vector109:
    push qword 0
    push qword 109
    jmp trampoline
vector110:
    push qword 0
    push qword 110
    jmp trampoline
vector111:
    push qword 0
    push qword 111
    jmp trampoline
vector112:
    push qword 0
    push qword 112
    jmp trampoline
vector113:
    push qword 0
    push qword 113
    jmp trampoline
vector114:
    push qword 0
    push qword 114
    jmp trampoline
vector115:
    push qword 0
    push qword 115
    jmp trampoline
vector116:
    push qword 0
    push qword 116
    jmp trampoline
vector117:
    push qword 0
    push qword 117
    jmp trampoline
vector118:
    push qword 0
    push qword 118
    jmp trampoline
vector119:
    push qword 0
    push qword 119
    jmp trampoline
vector120:
    push qword 0
    push qword 120
    jmp trampoline
vector121:
    push qword 0
    push qword 121
    jmp trampoline
vector122:
    push qword 0
    push qword 122
    jmp trampoline
vector123:
    push qword 0
    push qword 123
    jmp trampoline
vector124:
    push qword 0
    push qword 124
    jmp trampoline
vector125:
    push qword 0
    push qword 125
    jmp trampoline
vector126:
    push qword 0
    push qword 126
    jmp trampoline
vector127:
    push qword 0
    push qword 127
    jmp trampoline
vector128:
    push qword 0
    push qword 128
    jmp trampoline
vector129:
    push qword 0
    push qword 129
    jmp trampoline
vector130:
    push qword 0
    push qword 130
    jmp trampoline
vector131:
    push qword 0
    push qword 131
    jmp trampoline
vector132:
    push qword 0
    push qword 132
    jmp trampoline
vector133:
    push qword 0
    push qword 133
    jmp trampoline
vector134:
    push qword 0
    push qword 134
    jmp trampoline
vector135:
    push qword 0
    push qword 135
    jmp trampoline
vector136:
    push qword 0
    push qword 136
    jmp trampoline
vector137:
    push qword 0
    push qword 137
    jmp trampoline
vector138:
    push qword 0
    push qword 138
    jmp trampoline
vector139:
    push qword 0
    push qword 139
    jmp trampoline
vector140:
    push qword 0
    push qword 140
    jmp trampoline
vector141:
    push qword 0
    push qword 141
    jmp trampoline
vector142:
    push qword 0
    push qword 142
    jmp trampoline
vector143:
    push qword 0
    push qword 143
    jmp trampoline
vector144:
    push qword 0
    push qword 144
    jmp trampoline
vector145:
    push qword 0
    push qword 145
    jmp trampoline
vector146:
    push qword 0
    push qword 146
    jmp trampoline
vector147:
    push qword 0
    push qword 147
    jmp trampoline
vector148:
    push qword 0
    push qword 148
    jmp trampoline
vector149:
    push qword 0
    push qword 149
    jmp trampoline
vector150:
    push qword 0
    push qword 150
    jmp trampoline
vector151:
    push qword 0
    push qword 151
    jmp trampoline
vector152:
    push qword 0
    push qword 152
    jmp trampoline
vector153:
    push qword 0
    push qword 153
    jmp trampoline
vector154:
    push qword 0
    push qword 154
    jmp trampoline
vector155:
    push qword 0
    push qword 155
    jmp trampoline
vector156:
    push qword 0
    push qword 156
    jmp trampoline
vector157:
    push qword 0
    push qword 157
    jmp trampoline
vector158:
    push qword 0
    push qword 158
    jmp trampoline
vector159:
    push qword 0
    push qword 159
    jmp trampoline
vector160:
    push qword 0
    push qword 160
    jmp trampoline
vector161:
    push qword 0
    push qword 161
    jmp trampoline
vector162:
    push qword 0
    push qword 162
    jmp trampoline
vector163:
    push qword 0
    push qword 163
    jmp trampoline
vector164:
    push qword 0
    push qword 164
    jmp trampoline
vector165:
    push qword 0
    push qword 165
    jmp trampoline
vector166:
    push qword 0
    push qword 166
    jmp trampoline
vector167:
    push qword 0
    push qword 167
    jmp trampoline
vector168:
    push qword 0
    push qword 168
    jmp trampoline
vector169:
    push qword 0
    push qword 169
    jmp trampoline
vector170:
    push qword 0
    push qword 170
    jmp trampoline
vector171:
    push qword 0
    push qword 171
    jmp trampoline
vector172:
    push qword 0
    push qword 172
    jmp trampoline
vector173:
    push qword 0
    push qword 173
    jmp trampoline
vector174:
    push qword 0
    push qword 174
    jmp trampoline
vector175:
    push qword 0
    push qword 175
    jmp trampoline
vector176:
    push qword 0
    push qword 176
    jmp trampoline
vector177:
    push qword 0
    push qword 177
    jmp trampoline
vector178:
    push qword 0
    push qword 178
    jmp trampoline
vector179:
    push qword 0
    push qword 179
    jmp trampoline
vector180:
    push qword 0
    push qword 180
    jmp trampoline
vector181:
    push qword 0
    push qword 181
    jmp trampoline
vector182:
    push qword 0
    push qword 182
    jmp trampoline
vector183:
    push qword 0
    push qword 183
    jmp trampoline
vector184:
    push qword 0
    push qword 184
    jmp trampoline
vector185:
    push qword 0
    push qword 185
    jmp trampoline
vector186:
    push qword 0
    push qword 186
    jmp trampoline
vector187:
    push qword 0
    push qword 187
    jmp trampoline
vector188:
    push qword 0
    push qword 188
    jmp trampoline
vector189:
    push qword 0
    push qword 189
    jmp trampoline
vector190:
    push qword 0
    push qword 190
    jmp trampoline
vector191:
    push qword 0
    push qword 191
    jmp trampoline
vector192:
    push qword 0
    push qword 192
    jmp trampoline
vector193:
    push qword 0
    push qword 193
    jmp trampoline
vector194:
    push qword 0
    push qword 194
    jmp trampoline
vector195:
    push qword 0
    push qword 195
    jmp trampoline
vector196:
    push qword 0
    push qword 196
    jmp trampoline
vector197:
    push qword 0
    push qword 197
    jmp trampoline
vector198:
    push qword 0
    push qword 198
    jmp trampoline
vector199:
    push qword 0
    push qword 199
    jmp trampoline
vector200:
    push qword 0
    push qword 200
    jmp trampoline
vector201:
    push qword 0
    push qword 201
    jmp trampoline
vector202:
    push qword 0
    push qword 202
    jmp trampoline
vector203:
    push qword 0
    push qword 203
    jmp trampoline
vector204:
    push qword 0
    push qword 204
    jmp trampoline
vector205:
    push qword 0
    push qword 205
    jmp trampoline
vector206:
    push qword 0
    push qword 206
    jmp trampoline
vector207:
    push qword 0
    push qword 207
    jmp trampoline
vector208:
    push qword 0
    push qword 208
    jmp trampoline
vector209:
    push qword 0
    push qword 209
    jmp trampoline
vector210:
    push qword 0
    push qword 210
    jmp trampoline
vector211:
    push qword 0
    push qword 211
    jmp trampoline
vector212:
    push qword 0
    push qword 212
    jmp trampoline
vector213:
    push qword 0
    push qword 213
    jmp trampoline
vector214:
    push qword 0
    push qword 214
    jmp trampoline
vector215:
    push qword 0
    push qword 215
    jmp trampoline
vector216:
    push qword 0
    push qword 216
    jmp trampoline
vector217:
    push qword 0
    push qword 217
    jmp trampoline
vector218:
    push qword 0
    push qword 218
    jmp trampoline
vector219:
    push qword 0
    push qword 219
    jmp trampoline
vector220:
    push qword 0
    push qword 220
    jmp trampoline
vector221:
    push qword 0
    push qword 221
    jmp trampoline
vector222:
    push qword 0
    push qword 222
    jmp trampoline
vector223:
    push qword 0
    push qword 223
    jmp trampoline
vector224:
    push qword 0
    push qword 224
    jmp trampoline
vector225:
    push qword 0
    push qword 225
    jmp trampoline
vector226:
    push qword 0
    push qword 226
    jmp trampoline
vector227:
    push qword 0
    push qword 227
    jmp trampoline
vector228:
    push qword 0
    push qword 228
    jmp trampoline
vector229:
    push qword 0
    push qword 229
    jmp trampoline
vector230:
    push qword 0
    push qword 230
    jmp trampoline
vector231:
    push qword 0
    push qword 231
    jmp trampoline
vector232:
    push qword 0
    push qword 232
    jmp trampoline
vector233:
    push qword 0
    push qword 233
    jmp trampoline
vector234:
    push qword 0
    push qword 234
    jmp trampoline
vector235:
    push qword 0
    push qword 235
    jmp trampoline
vector236:
    push qword 0
    push qword 236
    jmp trampoline
vector237:
    push qword 0
    push qword 237
    jmp trampoline
vector238:
    push qword 0
    push qword 238
    jmp trampoline
vector239:
    push qword 0
    push qword 239
    jmp trampoline
vector240:
    push qword 0
    push qword 240
    jmp trampoline
vector241:
    push qword 0
    push qword 241
    jmp trampoline
vector242:
    push qword 0
    push qword 242
    jmp trampoline
vector243:
    push qword 0
    push qword 243
    jmp trampoline
vector244:
    push qword 0
    push qword 244
    jmp trampoline
vector245:
    push qword 0
    push qword 245
    jmp trampoline
vector246:
    push qword 0
    push qword 246
    jmp trampoline
vector247:
    push qword 0
    push qword 247
    jmp trampoline
vector248:
    push qword 0
    push qword 248
    jmp trampoline
vector249:
    push qword 0
    push qword 249
    jmp trampoline
vector250:
    push qword 0
    push qword 250
    jmp trampoline
vector251:
    push qword 0
    push qword 251
    jmp trampoline
vector252:
    push qword 0
    push qword 252
    jmp trampoline
vector253:
    push qword 0
    push qword 253
    jmp trampoline
vector254:
    push qword 0
    push qword 254
    jmp trampoline
vector255:
    push qword 0
    push qword 255
    jmp trampoline
SECTION .data
vector:
    dq vector0
    dq vector1
    dq vector2
    dq vector3
    dq vector4
    dq vector5
    dq vector6
    dq vector7
    dq vector8
    dq vector9
    dq vector10
    dq vector11
    dq vector12
    dq vector13
    dq vector14
    dq vector15
    dq vector16
    dq vector17
    dq vector18
    dq vector19
    dq vector20
    dq vector21
    dq vector22
    dq vector23
    dq vector24
    dq vector25
    dq vector26
    dq vector27
    dq vector28
    dq vector29
    dq vector30
    dq vector31
    dq vector32
    dq vector33
    dq vector34
    dq vector35
    dq vector36
    dq vector37
    dq vector38
    dq vector39
    dq vector40
    dq vector41
    dq vector42
    dq vector43
    dq vector44
    dq vector45
    dq vector46
    dq vector47
    dq vector48
    dq vector49
    dq vector50
    dq vector51
    dq vector52
    dq vector53
    dq vector54
    dq vector55
    dq vector56
    dq vector57
    dq vector58
    dq vector59
    dq vector60
    dq vector61
    dq vector62
    dq vector63
    dq vector64
    dq vector65
    dq vector66
    dq vector67
    dq vector68
    dq vector69
    dq vector70
    dq vector71
    dq vector72
    dq vector73
    dq vector74
    dq vector75
    dq vector76
    dq vector77
    dq vector78
    dq vector79
    dq vector80
    dq vector81
    dq vector82
    dq vector83
    dq vector84
    dq vector85
    dq vector86
    dq vector87
    dq vector88
    dq vector89
    dq vector90
    dq vector91
    dq vector92
    dq vector93
    dq vector94
    dq vector95
    dq vector96
    dq vector97
    dq vector98
    dq vector99
    dq vector100
    dq vector101
    dq vector102
    dq vector103
    dq vector104
    dq vector105
    dq vector106
    dq vector107
    dq vector108
    dq vector109
    dq vector110
    dq vector111
    dq vector112
    dq vector113
    dq vector114
    dq vector115
    dq vector116
    dq vector117
    dq vector118
    dq vector119
    dq vector120
    dq vector121
    dq vector122
    dq vector123
    dq vector124
    dq vector125
    dq vector126
    dq vector127
    dq vector128
    dq vector129
    dq vector130
    dq vector131
    dq vector132
    dq vector133
    dq vector134
    dq vector135
    dq vector136
    dq vector137
    dq vector138
    dq vector139
    dq vector140
    dq vector141
    dq vector142
    dq vector143
    dq vector144
    dq vector145
    dq vector146
    dq vector147
    dq vector148
    dq vector149
    dq vector150
    dq vector151
    dq vector152
    dq vector153
    dq vector154
    dq vector155
    dq vector156
    dq vector157
    dq vector158
    dq vector159
    dq vector160
    dq vector161
    dq vector162
    dq vector163
    dq vector164
    dq vector165
    dq vector166
    dq vector167
    dq vector168
    dq vector169
    dq vector170
    dq vector171
    dq vector172
    dq vector173
    dq vector174
    dq vector175
    dq vector176
    dq vector177
    dq vector178
    dq vector179
    dq vector180
    dq vector181
    dq vector182
    dq vector183
    dq vector184
    dq vector185
    dq vector186
    dq vector187
    dq vector188
    dq vector189
    dq vector190
    dq vector191
    dq vector192
    dq vector193
    dq vector194
    dq vector195
    dq vector196
    dq vector197
    dq vector198
    dq vector199
    dq vector200
    dq vector201
    dq vector202
    dq vector203
    dq vector204
    dq vector205
    dq vector206
    dq vector207
    dq vector208
    dq vector209
    dq vector210
    dq vector211
    dq vector212
    dq vector213
    dq vector214
    dq vector215
    dq vector216
    dq vector217
    dq vector218
    dq vector219
    dq vector220
    dq vector221
    dq vector222
    dq vector223
    dq vector224
    dq vector225
    dq vector226
    dq vector227
    dq vector228
    dq vector229
    dq vector230
    dq vector231
    dq vector232
    dq vector233
    dq vector234
    dq vector235
    dq vector236
    dq vector237
    dq vector238
    dq vector239
    dq vector240
    dq vector241
    dq vector242
    dq vector243
    dq vector244
    dq vector245
    dq vector246
    dq vector247
    dq vector248
    dq vector249
    dq vector250
    dq vector251
    dq vector252
    dq vector253
    dq vector254
    dq vector255
